config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :study_groups do
    resources :studies, only: [:index, :update, :create, :destroy]
  end
  resources :studies

  post 'create_study', to: 'studies#create'
  get 'studies', to: 'studies#index'
  patch 'update_study/:id', to: 'studies#update'
  delete 'destroy_study/:id', to: 'studies#destroy'

  get 'active_studies', to: 'studies#active'

end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delayed_jobs.rb
class DelayedJobs < ApplicationRecord
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :study
  belongs_to :subject

  after_save :audit

  def audit
  	Rails.logger.info "**************inside audit log************"
  	AuditJob.perform_later self  #queue
  	#AuditJob.perform_later self  #queue
    #enrollment = args[0]  #enrollment object
    study_name, subject_name = study.name, subject.name
    Rake::Task['hello:process'].invoke

  	file = File.join(File.dirname(__FILE__), 'audit.txt')
    File.open(file, 'a') { |f| f.puts "A subject named #{subject_name} , enrolled to a Study named #{study_name} with priority 0" }
  end
  def audit_new
  	Rails.logger.info "**************inside audit log************"
    study_name, subject_name = study.name, subject.name

  	file = File.join(File.dirname(__FILE__), 'audit.txt')
	  File.open(file, 'a') { |f| f.puts "A subject named is being enrolled with priority -5" }
  end

  handle_asynchronously :audit, queue: :least_priority
  # handle_asynchronously :audit_new, queue: :top_most_priority
end

app/models/site.rb
class Site < ApplicationRecord
  # belongs_to :study
  has_one :address, as: :addressable
end

app/models/study.rb
class Study < ApplicationRecord
    validates_presence_of :name
    validates_presence_of :drug
    validates_numericality_of :age_limit , :greater_than => 7
    validates_numericality_of :phase , :less_than_or_equal_to => 5
    after_save :send_email
    
    belongs_to :study_group , optional: true
    has_many :sites


    has_one_attached :my_image do |attachable|
        attachable.variant :thumb, resize: "100x100"
      end

    has_many :enrollments
    has_many :subjects , through: :enrollments

    scope :usable_drugs, -> { where("phase >= 4") }
    scope :under_trials, -> { where("phase < 4") }
    
    private

  def send_email
    StudyMailer.with( study: @study ).success_email.deliver_later
  end
end

app/models/study_group.rb
class StudyGroup < ApplicationRecord
    has_many :studies
    has_many :sites , through: :studies
end

app/models/subject.rb
class Subject < ApplicationRecord
has_one :address ,  as: :addressable
# has_and_belongs_to_many :studies

has_many :enrollments
has_many :studies , through: :enrollments
validates :blood_group, presence: true, inclusion: { in: ['b+', 'a+', 'b-', 'o-'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
     skip_before_action :verify_authenticity_token
    # after_action :demo_after_action, only: [:index]
    #   around_action :demo_around_action

    # before_action :find_study_group, only: [:index, :create]
    
    # def create
    #     @study = @study_group.studies.new(study_params)
    #     if @study.save
    #         render json: {notice: "Study created succesfully!!"}
    #     else
    #         render json: {notice: "Could not create study!!"}            
    #     end
    # end

    # def index
    #     # puts "index method called"
    #     @studies= @study_group.studies
    #     render json: @studies
    # end
    def new
        @study=Study.new
        
    end


    def create
        @study = Study.new(study_params)
        if @study.save
            # StudyMailer.with( study: @study ).success_email.deliver_later
            redirect_to studies_path
        else
            render :new           
        end
    end

    def index
        # puts "index method called"
        @studies= Study.all
        # render json: @studies
    end

    def update
        @study=Study.find(params[:id])
        if @study
            @study.update(study_params)
            redirect_to studies_path
            # render json: {notice: "Study updated successfully"}
        else
            render :new           
            # render json: {error: "Could not find study"}
        end
    end

    def destroy
        @study=Study.find(params[:id])
        if @study
            @study.destroy
            redirect_to studies_path
            # render json: {notice: "Study deleted successfully"}
        else
            render :new           
            # render json: {error: "Could not find study"}
        end
    end
    private

    def find_study_group
        @study_group = StudyGroup.find(params[:study_group_id])
        # byebug
        puts @study_group
      end

    def demo_after_action
        p "called after method"
    end

    def demo_around_action
        p "called at the beginning method"
        yield
        p "called after method"
    end

    def study_params
        params.require(:study).permit(:name,:age_limit,:drug,:phase,:study_group_id,:my_image)
    end
end

app/controllers/study_groups_controller.rb
class StudyGroupsController < ApplicationController
 def index
    @sg=StudyGroup.all
    render json:@sg

 end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniMedidata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/studies/_study.html.haml
%tr
  %td
    = study.name
  %td
    = study.age_limit
  %td
    = study.drug
  %td
    = study.phase
  %td
    = study.symptoms
  - if study.my_image.attached?
    %td
      = link_to 'Download File', rails_blob_path(study.my_image, disposition: 'attachment')

app/views/studies/active.html.erb
<h2> Rendering Active Studies Action </h2> 

app/views/studies/index.html.haml
%h1
  Studies #{link_to 'Add Study', new_study_path}
%a
%div{:style => "border: 1px solid;"}
  %table
    %tbody
      %tr
        %th Name
        %th Age Limit
        %th Drug
        %th Phase
        %th Symptoms
        %th Image
      - cache @studies do
        - @studies.each do |study|
          = render partial: 'study', locals: { study: study }

app/views/studies/new.html.erb
<h2 style="border-bottom: 1px solid;"> Create Study </h2>

<%if @study.errors.full_messages.present? %>
    <% @study.errors.full_messages.each do |msg| %>
        <ul>
        <li> <%= msg %> </li>
        </ul>

    <% end %>

<% end %>
<%= form_with(model: @study, local: true) do |f| %>
<p>
 <%= f.label 'Name'%>
 <%= f.text_field :name%>
 </p>
<p>
 <%= f.label 'Age limit'%>
 <%= f.number_field :age_limit %>
 </p>
 <p>
 <%= f.label 'Drug' %>
 <%= f.text_field :drug%>
 </p>
 <p>
 <%= f.label 'Phase' %>
 <%= f.number_field :phase%>
 </p>
 <p>
 <%= f.label 'Symptoms' %>
 <%= f.text_field :symptoms%>
 </p>
 <p>
 <%= f.label 'Study Group ' %>
 <%= f.number_field :study_group_id%>
 </p>
 <p>
    <%= f.file_field :my_image %>  </p>
 <%= f.submit %>
<% end %>